# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyperslop" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f69fcb5dd9d7771942e7d6f981b2cd7e53d060d1f052dca7358d763054c61989"
      url "https://github.com/hyperslop-systems/hyperslop-cli/releases/download/v#{version}/hyperslop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30f56c5e65a9d7f3e93f3b829e2d7a08c19903f5a93de1241350b9442e30800f"
      url "https://github.com/hyperslop-systems/hyperslop-cli/releases/download/v#{version}/hyperslop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6e4f9dc528f463ee8e514c7fb283151940b65b29c5bc8f5e77854abdda6c7b5"
      url "https://github.com/hyperslop-systems/hyperslop-cli/releases/download/v#{version}/hyperslop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "84210f4464188f3f9d48534eee0ad4fbc4bbe20ddd5b12e0bd57747a9e19b4f6"
      url "https://github.com/hyperslop-systems/hyperslop-cli/releases/download/v#{version}/hyperslop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hyperslop"
  desc "hyperslop is the agent/customer CLI for the datadrop backend"
  homepage "https://github.com/hyperslop-systems/hyperslop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hyperslop"

  # No zap stanza required

end
